### ISSUE TITLE
July 8 

### ISSUE THREAD

**Issue by bpbond** [asl1219/meta-PNNL-2021#1]
Good discussion yesterday—thanks. After or as you finalize the first data analysis exercise, here are some next steps:

* Meet with Shoshi to learn about her meta-analysis work
* Download the global soil respiration database – https://github.com/bpbond/srdb - in particular, the “srdb-data.csv” file in it, along with the “srdb-data_fields.txt” metadata file
* Add the csv file to your repository and commit that change
* Add basic code to your analysis R Markdown to
* Read in the CSV file
* Select just a few columns for now, to keep things manageable. In particular, you’ll want latitude, longitude, study midyear, ecosystem type, manipulation, Rs_annual, and RC_annual
* Report how many observations (rows) we have for each ecosystem type

**Comment by bpbond** [comment]
Nice job! Step 2 for this week:

* Let's visualize RC_annual (the fraction of root contribution to total Rs) by latitude, ecosystem type, and Rs_annual
* We'd like to include climate data from the WorldClim database—that is, compute mean annual temperature and precipitation for each lat, Lon pair in our data
* I would suggest using @stephpenn1 's code as a starting point: see lines 333-384 in [this file](https://github.com/bpbond/cosore/blob/master/gcb/gcb_ms.Rmd)
* You can adapt and bring this code into your R Markdown to calculate and include these climate data

**Comment by bpbond** [comment]
You will want to EXCLUDE the worldclim data from git (in the .gitignore file)

See https://github.com/bpbond/cosore/blob/master/gcb/.gitignore

**Comment by bpbond** [comment]
Happy Monday!

* Get [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed — note steps 1 and 2
* Then proceed to build and install (hopefully) raster etc.
* That should be the toolchain you need for the worldclim stuff above

**Comment by asl1219** [comment]
Work done (besides small error mentioned in pull request)

**Comment by bpbond** [comment]
In general, I would say don't close issues until the PR is merged. And here specifically, that "small error" is a pretty big one :)

**Comment by asl1219** [comment]
7/26 To Do

1. Filter SRDB for interest (RC_annual)
2. Load in, match, and compute climate data (current R issues)
3. Visualize and summarize (graphs)
